### ISSUE TITLE
No favicon icon on the website

### ISSUE THREAD

**Issue by SumitVerma-coder** [ServiceToMankind/OpenCodeLaw#10]
Currently no favicon icon is present on the website.
![image](https://github.com/ServiceToMankind/OpenCodeLaw/assets/112965155/0431af97-9b2c-4dff-bae4-2d442dcaf3cb)
**_PLEASE ASSIGN ME THIS ISSUE UNDER HACTOBERFEST TAG_**

**Comment by KiranPranay** [comment]
@SumitVerma-coder , please use the following favicons.

https://github.com/ServiceToMankind/OpenCodeLaw/tree/main/favicons (310*310px recommended) .

**Comment by SumitVerma-coder** [comment]
ok

**Comment by SumitVerma-coder** [comment]
Used the requested favicons. Please look into the PR

**Comment by KiranPranay** [comment]
> Used the requested favicons. Please look into the PR

Yeah, Thank you 👍🏼
