### ISSUE TITLE
add smooth scrolling and a bottom to up button

### ISSUE THREAD

**Issue by Arnabhit** [ServiceToMankind/OpenCodeLaw#14]
I want to add the smooth scrolling effect whenever a content is clicked and a bottom to up button to return to top when the page is scrolled downwards.

**Comment by deepak4566** [comment]
Thanks for address it🎉 , i think u can solve issue so I'm assigning to u

**Comment by KiranPranay** [comment]
Its done, thank you.
https://github.com/ServiceToMankind/OpenCodeLaw/pull/18
