### ISSUE TITLE
Creating the Dark/Light theme toggle.

### ISSUE THREAD

**Issue by VanshSh** [ServiceToMankind/OpenCodeLaw#22]
- Creating the toggle on the top to switch to a Dark/Light theme.

**Comment by Raghu1124** [comment]
hey I would like to work on it. please assign me this issue

**Comment by VanshSh** [comment]
@@Raghu1124 I have already completed this task and also created the PR.

@deepak4566  I request you to please go through the PR and please merge it.

**Comment by KiranPranay** [comment]
Thank you 🥇
